{% set name = "pyrage" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyrage-{{ version }}.tar.gz
  sha256: 7a66dc84c624f7fdd43462c221c58a3c5b75744ceb0600fd75f41bf590af8e5b

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=0.14,<0.15
    - pip
  run:
    - python

test:
  imports:
    - pyrage
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/woodruffw/pyrage
  summary: Python bindings for rage (age in Rust)
  license: MIT
  license_file:
    - LICENSE
    - pyrage-stubs/LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - pavelzw
