{% set name = "pyrage" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyrage-{{ version }}.tar.gz
  sha256: d14cf05da3f66ed57e625a5269e1e8804a53be83c6689d77f2bfc49e9794b6ef

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=0.14,<0.15  # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=0.14,<0.15
    - pip
  run:
    - python

test:
  imports:
    - pyrage
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/woodruffw/pyrage
  summary: Python bindings for rage (age in Rust)
  license: MIT
  license_file:
    - LICENSE
    - pyrage-stubs/LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - pavelzw
