{% set name = "pyrage" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyrage-{{ version }}.tar.gz
  sha256: b283a2e3d688cbf68c707f57d93fdab3304ff57c7e2e6b710c0b4bc9096ad9da

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=0.14,<0.15  # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=0.14,<0.15
    - pip
  run:
    - python

test:
  imports:
    - pyrage
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/woodruffw/pyrage
  summary: Python bindings for rage (age in Rust)
  license: MIT
  license_file:
    - LICENSE
    - pyrage-stubs/LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - pavelzw
