schema_version: 1

context:
  name: pyrage
  version: "1.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyrage-${{ version }}.tar.gz
  sha256: 545bf188e8d217ec88c32bc8e8bf56026c8c0b1b1f96d2688cedf1427ab0e827

build:
  number: 0

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1.0,<2.0
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - pyrage
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: Python bindings for rage (age in Rust)
  license: MIT
  license_file:
    - LICENSE
    - pyrage-stubs/LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/woodruffw/pyrage

extra:
  recipe-maintainers:
    - pavelzw
